'use client'

import { Toolbar } from '@mui/material';
import Head from 'next/head'
import LayoutNoApp from 'src/views/layouts/LayoutNoApp';
import HomePage from 'src/views/pages/home';

export default function Home() {


  return (
    <>
      <Head>
        <title>SHOP APP</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Toolbar></Toolbar>
      <HomePage></HomePage>
    </>
  )
}


Home.getLayout = (page: React.ReactNode) => <LayoutNoApp>{page}</LayoutNoApp>
Home.guestGuard = false;
Home.authGuard = false;