'use client'

import { Box, useTheme } from '@mui/material'
import Head from 'next/head'
import CustomTextField from 'src/components/text-field';
import LayoutNoApp from 'src/views/layouts/LayoutNoApp';

export default function Home() {


  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}


Home.getLayout = (page : React.ReactNode) => <LayoutNoApp>{page}</LayoutNoApp>
Home.guestGuard = false;
Home.authGuard = false;